spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share
  profiles:
     active: native
  config:
    name: xyb2b-config-server

server:
  port: 8888
  
service:
  config:
    imgPrefix: http://img0.xyb2b.com/
  
foo: hi this is foo!!!