spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/share
  profiles:
     active: native
  config:
    name: ds-config-server

server:
  port: 8888
  
foo: hi this is foo!!!