server:
  port: 8763
  
spring:
  application:
    name: order-service
  profiles:
    active: orderservice
  cloud:
    config:
      uri: http://localhost:8888
      profile: orderservice
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/