server:
  port: 8762


spring:
  application:
    name: gateway-service
  profiles:
    active: gateway
  cloud:
    config:
      uri: http://localhost:8888
      profile: gateway

zuul:
  routes:
    consumer:
      path: /user/**
      service-id: user-service
      stripPrefix: false
      sensitiveHeaders:

feign:
  hystrix:
    enabled: true

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/