server:
  port: 8765

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
spring:
  application:
    name: service-dashborad
  profiles:
    active: dashborad
  cloud:
    config:
      uri: http://localhost:8888
      profile: dashborad
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/