server:
  port: 8764
  context-path:/user
  
hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
      
spring:
  application:
    name: user-service
  profiles:
    active: userservice
  cloud:
    config:
      uri: http://localhost:8888
      profile: userservice
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 